### ISSUE TITLE
"Unknown handler: file" error when tutorial app is launching on Heroku

### ISSUE THREAD

**Issue by johndevor** [electrode-io/electrode-server#19]
Walking through the tutorial documentation and I receive this error when trying to start the app on Heroku. 

> Starting standalone server in PROD mode
> 
> ESERVERSTART
> 
> This error is thrown by the electrode-server module
> There was an error starting the Hapi.js server
> Please check the output of the stack trace below and correct the error shown
> error, please file an issue on the electrode-server repository
> 
> If you have followed this resolution step and you are still seeing an
> 
> 
> git+https://github.com/electrode-io/electrode-server.git
>    
> Unknown handler: file
> at internals.Connection._addRoute (/app/node_modules/hapi/lib/connection.js:412:19)
>  Unhandled rejection Error: Unknown handler: file
> at Object.exports.assert (/app/node_modules/hapi/node_modules/hoek/lib/index.js:736:11)
> at Object.exports.defaults (/app/node_modules/hapi/lib/handler.js:108:14)
> at new module.exports.internals.Route (/app/node_modules/hapi/lib/route.js:60:37)
> at Object.target [as register] (/app/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
> at internals.Connection._route (/app/node_modules/hapi/lib/connection.js:404:18)
> at internals.Plugin._apply (/app/node_modules/hapi/lib/plugin.js:588:14)
> at internals.Plugin.route (/app/node_modules/hapi/lib/plugin.js:558:10)
> at Object.plugin.register (/app/server/plugins/pwa.js:7:10)
> at each (/app/node_modules/hapi/lib/plugin.js:318:14)
> at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
> at Promise (/app/node_modules/electrode-server/lib/electrode-server.js:118:14)
> at Object.exports.serial (/app/node_modules/hapi/node_modules/items/lib/index.js:39:9)
> at internals.Plugin.register (/app/node_modules/hapi/lib/plugin.js:321:11)
> at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:300:9)
> at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:481:18)
>  
> Register plugins is taking a while - If this takes longer than 10 seconds, then 
> double check your plugins to make sure each one calls next() at the end.
> Server will automatically abort after 20 seconds.
> 
>  
> State changed from starting to crashed
> Process exited with status 0

**Comment by johndevor** [comment]
Ok, closing my own issue. 

> heroku config:set STATIC_FILES_OFF=true

Caused the issue.
